### ISSUE TITLE
cycle_npreg_outsample takes excessive time

### ISSUE THREAD

**Issue by kennethabarr** [jhsiao999/peco#3]
cycle_npreg_outsample also draws trend lines and finds pva. This should be removed and placed in a separate function.

**Comment by jhsiao999** [comment]
Thanks @kennethabarr.

The excessive computing time is due to the step of re-estimating cyclic trends of gene expression based on the predicted cell cycle phase. I've now made this optional (see below for argument description). The default is F (don't re-estimate cyclic trends). 

Later user can choose to estimate cyclic trends of favorite genes using `fit_trendfilter_generic` or `fit_bspline`.

```
#' @param get_trend_estimates To re-estimate the cylic trend based on the predicted
#'   cell cycle phase or not (T or F). Default FALSE. This step calls trendfilter
#'   and is computationally intensive.
```
