### ISSUE TITLE
error with cycle_npreg_outsample() 

### ISSUE THREAD

**Issue by jhsiao999** [jhsiao999/peco#40]
Referencing an issue submitted via email

```
Error in (function (cl, name, valueClass) : assignment of an object of class “list” is not valid for @‘elementMetadata’ in an object of class “DFrame”; is(value, "DataTable_OR_NULL") is not TRUE

3. | stop(gettextf("assignment of an object of class %s is not valid for @%s in an object of class %s; is(value, \"%s\") is not TRUE", dQuote(valueClass), sQuote(name), dQuote(cl), slotClass), domain = NA)

2. (function (cl, name, valueClass) { ClassDef <- getClass(cl) slotClass <- ClassDef@slots[[name]] ...

1. cycle_npreg_outsample(Y_test = MGH1518sce, sigma_est = training_human$sigma[rownames(MGH1518sce), ], funs_est = training_human$cellcycle_function[rownames(MGH1518sce)], method.trend = "trendfilter", ncores = 1, get_trend_estimates = FALSE)

```

**Comment by npojo** [comment]
I have encountered this error and tracked it to: 
`colData(Y_test)@elementMetadata$labelDescription[ncol(colData(Y_test))] <- "peco predicted continuous cell cycle, between 0 to 2pi"`
This is probably due to `@elementMetadata` of `colData `being `NULL`. I simply commented this line which I guess is not crucial.

**Comment by jhsiao999** [comment]
@npojo Thank you for the feedback. Much appreciated. I've fixed the code to allow input with empty colData slot. You can install the updated version from the master branch.
